name: impact-of-lobbying-assignment
dependencies:
  - black~=26.1.0
  - ipykernel=7.1.0
  - matplotlib~=3.10.8
  - numpy~=2.4.1
  - openpyxl~=3.1.5
  - pandas~=2.3.3
  - pandas-stubs=2.3.3.260113
  - pip~=24.2.0
  - pyzmq~=27.1.0
  - requests~=2.32.5
  - seaborn~=0.13.2
  - statsmodels~=0.14.6
  - pip:
      - stargazer~=0.0.7
      - -e ./
